In [ ]:
import tabula
import pandas as pd
import numpy as np

In [74]:
stevenson = tabula.read_pdf("C:\\Users\\jmeye\\Documents\\4 - Stevenson Regional Tab Summary 2018.pdf", java_options=["-Dfile.encoding=UTF8"], pages=[1,2], lattice=True)
# stevenson.shape
stevenson=stevenson.drop(stevenson.index[14]).reset_index(drop=True)

In [3]:
# 
# def add_team_number(tab_df):
#     try:
#         team_numbers = []
#         for team_string in tab_df["Team"]:
#             team_number = team_string[:team_string.find("\r")]
#             team_number = int(team_number)
#             team_numbers.append(team_number)
#         team_numbers = pd.Series(team_numbers, name="Team Number")
#         tab_df.insert(0, "Team Number", team_numbers)
#     except ValueError:
#         pass
# 
# add_team_number(stevenson)

In [ ]:
# def format_team_name(tab_df):
#     for team_string_pair in tab_df["Team"].iteritems():
#         team_name = team_string_pair[1][team_string_pair[1].find("\r")+1:]
#         tab_df.at[team_string_pair[0], "Team"] = team_name.replace("\r", " ")
#         
# format_team_name(stevenson)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">Team</th>
    </tr>
    <tr>
      <th></th>
      <th>Number</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1009</td>
      <td>University of Maryland, College Park</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1012</td>
      <td>University of Maryland, College Park</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1089</td>
      <td>Stevenson</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1098</td>
      <td>University of Maryland, Baltimore County</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1099</td>
      <td>University of Maryland, Baltimore County</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1132</td>
      <td>University of Scranton</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1143</td>
      <td>Iona College</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1220</td>
      <td>Haverford College</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1221</td>
      <td>Haverford College</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1227</td>
      <td>College of William &amp; Mary</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1321</td>
      <td>Columbia University</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1322</td>
      <td>Columbia University</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1346</td>
      <td>Washington Adventist University</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1364</td>
      <td>St. Vincent College</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1419</td>
      <td>La Salle University</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1420</td>
      <td>La Salle University</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1441</td>
      <td>New York University</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1506</td>
      <td>Johns Hopkins University</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1508</td>
      <td>Franklin and Marshall College</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1549</td>
      <td>George Washington University</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1551</td>
      <td>George Washington University</td>
    </tr>
    <tr>
      <th>21</th>
      <td>1553</td>
      <td>Stevenson University</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1644</td>
      <td>Towson University</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1649</td>
      <td>Fordham University Rose Hill</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1685</td>
      <td>St. Vincent College</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1700</td>
      <td>Brooklyn College</td>
    </tr>
    <tr>
      <th>26</th>
      <td>1705</td>
      <td>City College of New York, CUNY</td>
    </tr>
    <tr>
      <th>27</th>
      <td>1803</td>
      <td>Bye-Buster Team</td>
    </tr>
  </tbody>
</table>
</div>

In [78]:
def generate_teams(tab_df):
    team_numbers = []
    team_names = []
    for team_string in tab_df["Team"]:
        team_number = team_string[:team_string.find("\r")]
        team_number = int(team_number)
        team_name = team_string[team_string.find("\r")+1:]
        team_name = team_name.replace("\r", " ")
        team_names.append(team_name)
        team_numbers.append(team_number)
    index = pd.MultiIndex.from_tuples([("Team", "Number"),("Team", "Name")])
    data = np.array([team_numbers,team_names]).T
    formatted_data = pd.DataFrame(data, columns=index)
    return formatted_data

generate_teams(stevenson)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">Team</th>
    </tr>
    <tr>
      <th></th>
      <th>Number</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1009</td>
      <td>University of Maryland, College Park</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1012</td>
      <td>University of Maryland, College Park</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1089</td>
      <td>Stevenson</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1098</td>
      <td>University of Maryland, Baltimore County</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1099</td>
      <td>University of Maryland, Baltimore County</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1132</td>
      <td>University of Scranton</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1143</td>
      <td>Iona College</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1220</td>
      <td>Haverford College</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1221</td>
      <td>Haverford College</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1227</td>
      <td>College of William &amp; Mary</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1321</td>
      <td>Columbia University</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1322</td>
      <td>Columbia University</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1346</td>
      <td>Washington Adventist University</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1364</td>
      <td>St. Vincent College</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1419</td>
      <td>La Salle University</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1420</td>
      <td>La Salle University</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1441</td>
      <td>New York University</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1506</td>
      <td>Johns Hopkins University</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1508</td>
      <td>Franklin and Marshall College</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1549</td>
      <td>George Washington University</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1551</td>
      <td>George Washington University</td>
    </tr>
    <tr>
      <th>21</th>
      <td>1553</td>
      <td>Stevenson University</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1644</td>
      <td>Towson University</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1649</td>
      <td>Fordham University Rose Hill</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1685</td>
      <td>St. Vincent College</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1700</td>
      <td>Brooklyn College</td>
    </tr>
    <tr>
      <th>26</th>
      <td>1705</td>
      <td>City College of New York, CUNY</td>
    </tr>
    <tr>
      <th>27</th>
      <td>1803</td>
      <td>Bye-Buster Team</td>
    </tr>
  </tbody>
</table>
</div>

In [50]:
def generate_summary(tab_df):
    ballots_won = []
    ballots_lost = []
    ballots_tied = []
    total_ballots = []
    cs = []
    ocs = []
    pds = []
    for team_summary_pair in tab_df["Summary"].iteritems():
        team_wins = int(team_summary_pair[1][0])
        team_losses = int(team_summary_pair[1][2])
        team_ties = int(team_summary_pair[1][4])
        team_score = team_wins + (.5) * team_ties
        details = team_summary_pair[1][14:]
        cs_digits = 1
        if details[0] == "1" or details[0] == "2":
            cs_digits = 2
        else:
            pass
        if details[cs_digits] == ".":
            cs_digits += 2
        team_cs = float(details[0:cs_digits])
        details = details[cs_digits:]
        pd_start = max(details.find("+"), details.find("-"), details.find("#"))
        team_ocs = float(details[:pd_start])
        team_pd = ""
        if details[pd_start] != "#": 
            team_pd = int(details[pd_start:])
        ballots_won.append(team_wins)
        ballots_lost.append(team_losses)
        ballots_tied.append(team_ties)
        total_ballots.append(team_score)
        cs.append(team_cs)
        ocs.append(team_ocs)
        pds.append(team_pd)
    index_tuples = list(zip(["Summary"]*7,["Ballots Won","Ballots Lost","Ballots Tied","CS","OCS","PD","Score"]))
    index = pd.MultiIndex.from_tuples(index_tuples)
    data = [ballots_won,ballots_lost,ballots_tied,cs,ocs,pds,total_ballots]
    data = np.array(data).T
    formatted_data = pd.DataFrame(data,columns=index)
    return formatted_data

In [51]:

generate_summary(stevenson)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="7" halign="left">Summary</th>
    </tr>
    <tr>
      <th></th>
      <th>Ballots Won</th>
      <th>Ballots Lost</th>
      <th>Ballots Tied</th>
      <th>CS</th>
      <th>OCS</th>
      <th>PD</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>16.0</td>
      <td>66.0</td>
      <td>46</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>6</td>
      <td>2</td>
      <td>0</td>
      <td>12.5</td>
      <td>77.0</td>
      <td>32</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>5</td>
      <td>1</td>
      <td>20.0</td>
      <td>53.0</td>
      <td>3</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>7</td>
      <td>1</td>
      <td>0</td>
      <td>13.0</td>
      <td>79.5</td>
      <td></td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>2</td>
      <td>1</td>
      <td>14.0</td>
      <td>70.0</td>
      <td>30</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1</td>
      <td>7</td>
      <td>0</td>
      <td>12.5</td>
      <td>56.5</td>
      <td>-63</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>17.0</td>
      <td>52.0</td>
      <td></td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>5</td>
      <td>3</td>
      <td>0</td>
      <td>20.5</td>
      <td>62.0</td>
      <td>36</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>22.5</td>
      <td>54.0</td>
      <td>-3</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>5</td>
      <td>3</td>
      <td>0</td>
      <td>9.5</td>
      <td>73.5</td>
      <td>87</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>7</td>
      <td>1</td>
      <td>0</td>
      <td>17.0</td>
      <td>67.0</td>
      <td></td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>8</td>
      <td>0</td>
      <td>0</td>
      <td>13.0</td>
      <td>79.5</td>
      <td>98</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>20.5</td>
      <td>56.0</td>
      <td>-71</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>3</td>
      <td>4</td>
      <td>1</td>
      <td>18.5</td>
      <td>62.0</td>
      <td>-52</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>14</th>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>14.5</td>
      <td>74.5</td>
      <td></td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>15</th>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>17.5</td>
      <td>58.5</td>
      <td>-42</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>20.0</td>
      <td>60.5</td>
      <td>-12</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>22.0</td>
      <td>65.5</td>
      <td>-19</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>15.5</td>
      <td>60.5</td>
      <td>-199</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>15.5</td>
      <td>72.5</td>
      <td>60</td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>20</th>
      <td>8</td>
      <td>0</td>
      <td>0</td>
      <td>14.0</td>
      <td>72.5</td>
      <td>70</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>2</td>
      <td>5</td>
      <td>1</td>
      <td>18.5</td>
      <td>63.0</td>
      <td>-35</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1</td>
      <td>7</td>
      <td>0</td>
      <td>11.0</td>
      <td>56.0</td>
      <td>-44</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>18.0</td>
      <td>67.5</td>
      <td>24</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0</td>
      <td>8</td>
      <td>0</td>
      <td>10.5</td>
      <td>69.5</td>
      <td>-156</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>20.0</td>
      <td>46.0</td>
      <td>-162</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>12.5</td>
      <td>56.5</td>
      <td>-70</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>12.0</td>
      <td>61.0</td>
      <td>-61</td>
      <td>4.0</td>
    </tr>
  </tbody>
</table>
</div>

In [79]:
generate_teams(stevenson).join(generate_summary(stevenson))

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="5" halign="left">Round 1</th>
      <th colspan="5" halign="left">Round 2</th>
      <th colspan="5" halign="left">Round 3</th>
      <th colspan="5" halign="left">Round 4</th>
    </tr>
    <tr>
      <th></th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>D</td>
      <td>1551</td>
      <td>-5</td>
      <td>-6</td>
      <td>0</td>
      <td>P</td>
      <td>1220</td>
      <td>-8</td>
      <td>-8</td>
      <td>0</td>
      <td>D</td>
      <td>1346</td>
      <td>16</td>
      <td>21</td>
      <td>2</td>
      <td>P</td>
      <td>1644</td>
      <td>8</td>
      <td>28</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>P</td>
      <td>1346</td>
      <td>9</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1420</td>
      <td>-6</td>
      <td>14</td>
      <td>1</td>
      <td>P</td>
      <td>1553</td>
      <td>14</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1220</td>
      <td>-10</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>P</td>
      <td>1419</td>
      <td>-1</td>
      <td>0</td>
      <td>0.5</td>
      <td>D</td>
      <td>1685</td>
      <td>17</td>
      <td>10</td>
      <td>2</td>
      <td>P</td>
      <td>1099</td>
      <td>-6</td>
      <td>-3</td>
      <td>0</td>
      <td>D</td>
      <td>1551</td>
      <td>-1</td>
      <td>-13</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>P</td>
      <td>1221</td>
      <td>4</td>
      <td>-2</td>
      <td>1</td>
      <td>D</td>
      <td>1700</td>
      <td>28</td>
      <td>25</td>
      <td>2</td>
      <td>P</td>
      <td>1441</td>
      <td>2</td>
      <td>40</td>
      <td>2</td>
      <td>D</td>
      <td>1143</td>
      <td>2</td>
      <td>18</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>P</td>
      <td>1705</td>
      <td>17</td>
      <td>26</td>
      <td>2</td>
      <td>D</td>
      <td>1506</td>
      <td>-17</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1089</td>
      <td>6</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1549</td>
      <td>6</td>
      <td>0</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>5</th>
      <td>D</td>
      <td>1227</td>
      <td>-15</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1364</td>
      <td>-12</td>
      <td>-4</td>
      <td>0</td>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>-6</td>
      <td>1</td>
      <td>P</td>
      <td>1420</td>
      <td>-3</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P</td>
      <td>1685</td>
      <td>46</td>
      <td>31</td>
      <td>2</td>
      <td>D</td>
      <td>1508</td>
      <td>24</td>
      <td>35</td>
      <td>2</td>
      <td>D</td>
      <td>1322</td>
      <td>-1</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-2</td>
      <td>-18</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>P</td>
      <td>1649</td>
      <td>5</td>
      <td>11</td>
      <td>2</td>
      <td>D</td>
      <td>1009</td>
      <td>8</td>
      <td>8</td>
      <td>2</td>
      <td>D</td>
      <td>1549</td>
      <td>-1</td>
      <td>-2</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>10</td>
      <td>-3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>D</td>
      <td>1098</td>
      <td>-4</td>
      <td>2</td>
      <td>1</td>
      <td>P</td>
      <td>1322</td>
      <td>-8</td>
      <td>-3</td>
      <td>0</td>
      <td>P</td>
      <td>1227</td>
      <td>7</td>
      <td>-10</td>
      <td>1</td>
      <td>D</td>
      <td>1553</td>
      <td>4</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>P</td>
      <td>1132</td>
      <td>15</td>
      <td>23</td>
      <td>2</td>
      <td>D</td>
      <td>1553</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>D</td>
      <td>1221</td>
      <td>-7</td>
      <td>10</td>
      <td>1</td>
      <td>P</td>
      <td>1700</td>
      <td>32</td>
      <td>22</td>
      <td>2</td>
    </tr>
    <tr>
      <th>10</th>
      <td>P</td>
      <td>1803</td>
      <td>47</td>
      <td>29</td>
      <td>2</td>
      <td>D</td>
      <td>1419</td>
      <td>-3</td>
      <td>1</td>
      <td>1</td>
      <td>D</td>
      <td>1506</td>
      <td>15</td>
      <td>9</td>
      <td>2</td>
      <td>P</td>
      <td>1364</td>
      <td>23</td>
      <td>19</td>
      <td>2</td>
    </tr>
    <tr>
      <th>11</th>
      <td>P</td>
      <td>1700</td>
      <td>24</td>
      <td>51</td>
      <td>2</td>
      <td>D</td>
      <td>1221</td>
      <td>8</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>1</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1441</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>12</th>
      <td>D</td>
      <td>1012</td>
      <td>-9</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1549</td>
      <td>-23</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1009</td>
      <td>-16</td>
      <td>-21</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>15</td>
      <td>7</td>
      <td>2</td>
    </tr>
    <tr>
      <th>13</th>
      <td>P</td>
      <td>1553</td>
      <td>9</td>
      <td>0</td>
      <td>1.5</td>
      <td>D</td>
      <td>1132</td>
      <td>12</td>
      <td>4</td>
      <td>2</td>
      <td>P</td>
      <td>1551</td>
      <td>-17</td>
      <td>-18</td>
      <td>0</td>
      <td>D</td>
      <td>1321</td>
      <td>-23</td>
      <td>-19</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>D</td>
      <td>1089</td>
      <td>1</td>
      <td>0</td>
      <td>1.5</td>
      <td>P</td>
      <td>1321</td>
      <td>3</td>
      <td>-1</td>
      <td>1</td>
      <td>D</td>
      <td>1508</td>
      <td>38</td>
      <td>78</td>
      <td>2</td>
      <td>P</td>
      <td>1506</td>
      <td>5</td>
      <td>8</td>
      <td>2</td>
    </tr>
    <tr>
      <th>15</th>
      <td>D</td>
      <td>1549</td>
      <td>-5</td>
      <td>-12</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>6</td>
      <td>-14</td>
      <td>1</td>
      <td>P</td>
      <td>1649</td>
      <td>-10</td>
      <td>-12</td>
      <td>0</td>
      <td>D</td>
      <td>1132</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>16</th>
      <td>P</td>
      <td>1506</td>
      <td>17</td>
      <td>-7</td>
      <td>1</td>
      <td>D</td>
      <td>1705</td>
      <td>3</td>
      <td>27</td>
      <td>2</td>
      <td>D</td>
      <td>1098</td>
      <td>-2</td>
      <td>-40</td>
      <td>0</td>
      <td>P</td>
      <td>1322</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>D</td>
      <td>1441</td>
      <td>-17</td>
      <td>7</td>
      <td>1</td>
      <td>P</td>
      <td>1099</td>
      <td>17</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1321</td>
      <td>-15</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1419</td>
      <td>-5</td>
      <td>-8</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>-24</td>
      <td>-35</td>
      <td>0</td>
      <td>P</td>
      <td>1419</td>
      <td>-38</td>
      <td>-78</td>
      <td>0</td>
      <td>D</td>
      <td>1649</td>
      <td>-19</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>P</td>
      <td>1420</td>
      <td>5</td>
      <td>12</td>
      <td>2</td>
      <td>D</td>
      <td>1346</td>
      <td>23</td>
      <td>23</td>
      <td>2</td>
      <td>P</td>
      <td>1220</td>
      <td>1</td>
      <td>2</td>
      <td>2</td>
      <td>D</td>
      <td>1099</td>
      <td>-6</td>
      <td>0</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>20</th>
      <td>P</td>
      <td>1009</td>
      <td>5</td>
      <td>6</td>
      <td>2</td>
      <td>D</td>
      <td>1649</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
      <td>D</td>
      <td>1364</td>
      <td>17</td>
      <td>18</td>
      <td>2</td>
      <td>P</td>
      <td>1089</td>
      <td>1</td>
      <td>13</td>
      <td>2</td>
    </tr>
    <tr>
      <th>21</th>
      <td>D</td>
      <td>1364</td>
      <td>-9</td>
      <td>0</td>
      <td>0.5</td>
      <td>P</td>
      <td>1227</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1012</td>
      <td>-14</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1221</td>
      <td>-4</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>P</td>
      <td>1508</td>
      <td>-2</td>
      <td>-2</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1132</td>
      <td>-2</td>
      <td>6</td>
      <td>1</td>
      <td>D</td>
      <td>1009</td>
      <td>-8</td>
      <td>-28</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>D</td>
      <td>1220</td>
      <td>-5</td>
      <td>-11</td>
      <td>0</td>
      <td>P</td>
      <td>1551</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1420</td>
      <td>10</td>
      <td>12</td>
      <td>2</td>
      <td>P</td>
      <td>1508</td>
      <td>19</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>24</th>
      <td>D</td>
      <td>1143</td>
      <td>-46</td>
      <td>-31</td>
      <td>0</td>
      <td>P</td>
      <td>1089</td>
      <td>-17</td>
      <td>-10</td>
      <td>0</td>
      <td>D</td>
      <td>1700</td>
      <td>-7</td>
      <td>-13</td>
      <td>0</td>
      <td>P</td>
      <td>1705</td>
      <td>-11</td>
      <td>-21</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>D</td>
      <td>1322</td>
      <td>-24</td>
      <td>-51</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-28</td>
      <td>-25</td>
      <td>0</td>
      <td>P</td>
      <td>1685</td>
      <td>7</td>
      <td>13</td>
      <td>2</td>
      <td>D</td>
      <td>1227</td>
      <td>-32</td>
      <td>-22</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>D</td>
      <td>1099</td>
      <td>-17</td>
      <td>-26</td>
      <td>0</td>
      <td>P</td>
      <td>1441</td>
      <td>-3</td>
      <td>-27</td>
      <td>0</td>
      <td>P</td>
      <td>1803</td>
      <td>-18</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1685</td>
      <td>11</td>
      <td>21</td>
      <td>2</td>
    </tr>
    <tr>
      <th>27</th>
      <td>D</td>
      <td>1321</td>
      <td>-47</td>
      <td>-29</td>
      <td>0</td>
      <td>P</td>
      <td>1644</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1705</td>
      <td>18</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1346</td>
      <td>-15</td>
      <td>-7</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [80]:
def generate_rounds(tab_df):
    rounds = []
    for i in range(4):
        roundnum = str(i+1)
        side = []
        opponent = []
        ballot1 = []
        ballot2 = []
        total_ballots = []
        for trial_string in tab_df["Round " + str(roundnum)]:
            if trial_string[0] == u'Π':
                side.append('P')
            else:
                side.append('D')
            opp = int(trial_string[3:7])
            opponent.append(opp)
            useful = trial_string[11:]
            nonties = useful.count("+") + useful.count("-")
            bal1 = 0
            bal2 = 0
            total = 0
            if nonties == 0:
                pass
            elif nonties == 1:
                bal1 = int(useful[:-1])
            else:
                second = max(useful.rfind("+"), useful.rfind("-"))
                bal1 = int(useful[:second])
                bal2 = int(useful[second:])
            ballot1.append(bal1)
            ballot2.append(bal2)
            for ballot in [bal1, bal2]:
                if ballot == 0:
                    total += 0.5
                elif ballot > 0:
                    total += 1
            total_ballots.append(total)
        data = np.array([side, opponent, ballot1, ballot2, total_ballots]).T
        index_tuples = list(zip(["Round " + roundnum]*5,["Side","Opponent","Ballot 1","Ballot 2","Total Ballots"]))
        index = pd.MultiIndex.from_tuples(index_tuples)
        formatted_round_data = pd.DataFrame(data,columns=index)
        rounds.append(formatted_round_data)
    all_rounds = rounds[0].join(rounds[1]).join(rounds[2]).join(rounds[3])
    return all_rounds

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="5" halign="left">Round 1</th>
      <th colspan="5" halign="left">Round 2</th>
      <th colspan="5" halign="left">Round 3</th>
      <th colspan="5" halign="left">Round 4</th>
    </tr>
    <tr>
      <th></th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>D</td>
      <td>1551</td>
      <td>-5</td>
      <td>-6</td>
      <td>0</td>
      <td>P</td>
      <td>1220</td>
      <td>-8</td>
      <td>-8</td>
      <td>0</td>
      <td>D</td>
      <td>1346</td>
      <td>16</td>
      <td>21</td>
      <td>2</td>
      <td>P</td>
      <td>1644</td>
      <td>8</td>
      <td>28</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>P</td>
      <td>1346</td>
      <td>9</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1420</td>
      <td>-6</td>
      <td>14</td>
      <td>1</td>
      <td>P</td>
      <td>1553</td>
      <td>14</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1220</td>
      <td>-10</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>P</td>
      <td>1419</td>
      <td>-1</td>
      <td>0</td>
      <td>0.5</td>
      <td>D</td>
      <td>1685</td>
      <td>17</td>
      <td>10</td>
      <td>2</td>
      <td>P</td>
      <td>1099</td>
      <td>-6</td>
      <td>-3</td>
      <td>0</td>
      <td>D</td>
      <td>1551</td>
      <td>-1</td>
      <td>-13</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>P</td>
      <td>1221</td>
      <td>4</td>
      <td>-2</td>
      <td>1</td>
      <td>D</td>
      <td>1700</td>
      <td>28</td>
      <td>25</td>
      <td>2</td>
      <td>P</td>
      <td>1441</td>
      <td>2</td>
      <td>40</td>
      <td>2</td>
      <td>D</td>
      <td>1143</td>
      <td>2</td>
      <td>18</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>P</td>
      <td>1705</td>
      <td>17</td>
      <td>26</td>
      <td>2</td>
      <td>D</td>
      <td>1506</td>
      <td>-17</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1089</td>
      <td>6</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1549</td>
      <td>6</td>
      <td>0</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>5</th>
      <td>D</td>
      <td>1227</td>
      <td>-15</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1364</td>
      <td>-12</td>
      <td>-4</td>
      <td>0</td>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>-6</td>
      <td>1</td>
      <td>P</td>
      <td>1420</td>
      <td>-3</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P</td>
      <td>1685</td>
      <td>46</td>
      <td>31</td>
      <td>2</td>
      <td>D</td>
      <td>1508</td>
      <td>24</td>
      <td>35</td>
      <td>2</td>
      <td>D</td>
      <td>1322</td>
      <td>-1</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-2</td>
      <td>-18</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>P</td>
      <td>1649</td>
      <td>5</td>
      <td>11</td>
      <td>2</td>
      <td>D</td>
      <td>1009</td>
      <td>8</td>
      <td>8</td>
      <td>2</td>
      <td>D</td>
      <td>1549</td>
      <td>-1</td>
      <td>-2</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>10</td>
      <td>-3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>D</td>
      <td>1098</td>
      <td>-4</td>
      <td>2</td>
      <td>1</td>
      <td>P</td>
      <td>1322</td>
      <td>-8</td>
      <td>-3</td>
      <td>0</td>
      <td>P</td>
      <td>1227</td>
      <td>7</td>
      <td>-10</td>
      <td>1</td>
      <td>D</td>
      <td>1553</td>
      <td>4</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>P</td>
      <td>1132</td>
      <td>15</td>
      <td>23</td>
      <td>2</td>
      <td>D</td>
      <td>1553</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>D</td>
      <td>1221</td>
      <td>-7</td>
      <td>10</td>
      <td>1</td>
      <td>P</td>
      <td>1700</td>
      <td>32</td>
      <td>22</td>
      <td>2</td>
    </tr>
    <tr>
      <th>10</th>
      <td>P</td>
      <td>1803</td>
      <td>47</td>
      <td>29</td>
      <td>2</td>
      <td>D</td>
      <td>1419</td>
      <td>-3</td>
      <td>1</td>
      <td>1</td>
      <td>D</td>
      <td>1506</td>
      <td>15</td>
      <td>9</td>
      <td>2</td>
      <td>P</td>
      <td>1364</td>
      <td>23</td>
      <td>19</td>
      <td>2</td>
    </tr>
    <tr>
      <th>11</th>
      <td>P</td>
      <td>1700</td>
      <td>24</td>
      <td>51</td>
      <td>2</td>
      <td>D</td>
      <td>1221</td>
      <td>8</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>1</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1441</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>12</th>
      <td>D</td>
      <td>1012</td>
      <td>-9</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1549</td>
      <td>-23</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1009</td>
      <td>-16</td>
      <td>-21</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>15</td>
      <td>7</td>
      <td>2</td>
    </tr>
    <tr>
      <th>13</th>
      <td>P</td>
      <td>1553</td>
      <td>9</td>
      <td>0</td>
      <td>1.5</td>
      <td>D</td>
      <td>1132</td>
      <td>12</td>
      <td>4</td>
      <td>2</td>
      <td>P</td>
      <td>1551</td>
      <td>-17</td>
      <td>-18</td>
      <td>0</td>
      <td>D</td>
      <td>1321</td>
      <td>-23</td>
      <td>-19</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>D</td>
      <td>1089</td>
      <td>1</td>
      <td>0</td>
      <td>1.5</td>
      <td>P</td>
      <td>1321</td>
      <td>3</td>
      <td>-1</td>
      <td>1</td>
      <td>D</td>
      <td>1508</td>
      <td>38</td>
      <td>78</td>
      <td>2</td>
      <td>P</td>
      <td>1506</td>
      <td>5</td>
      <td>8</td>
      <td>2</td>
    </tr>
    <tr>
      <th>15</th>
      <td>D</td>
      <td>1549</td>
      <td>-5</td>
      <td>-12</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>6</td>
      <td>-14</td>
      <td>1</td>
      <td>P</td>
      <td>1649</td>
      <td>-10</td>
      <td>-12</td>
      <td>0</td>
      <td>D</td>
      <td>1132</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>16</th>
      <td>P</td>
      <td>1506</td>
      <td>17</td>
      <td>-7</td>
      <td>1</td>
      <td>D</td>
      <td>1705</td>
      <td>3</td>
      <td>27</td>
      <td>2</td>
      <td>D</td>
      <td>1098</td>
      <td>-2</td>
      <td>-40</td>
      <td>0</td>
      <td>P</td>
      <td>1322</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>D</td>
      <td>1441</td>
      <td>-17</td>
      <td>7</td>
      <td>1</td>
      <td>P</td>
      <td>1099</td>
      <td>17</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1321</td>
      <td>-15</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1419</td>
      <td>-5</td>
      <td>-8</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>-24</td>
      <td>-35</td>
      <td>0</td>
      <td>P</td>
      <td>1419</td>
      <td>-38</td>
      <td>-78</td>
      <td>0</td>
      <td>D</td>
      <td>1649</td>
      <td>-19</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>P</td>
      <td>1420</td>
      <td>5</td>
      <td>12</td>
      <td>2</td>
      <td>D</td>
      <td>1346</td>
      <td>23</td>
      <td>23</td>
      <td>2</td>
      <td>P</td>
      <td>1220</td>
      <td>1</td>
      <td>2</td>
      <td>2</td>
      <td>D</td>
      <td>1099</td>
      <td>-6</td>
      <td>0</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>20</th>
      <td>P</td>
      <td>1009</td>
      <td>5</td>
      <td>6</td>
      <td>2</td>
      <td>D</td>
      <td>1649</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
      <td>D</td>
      <td>1364</td>
      <td>17</td>
      <td>18</td>
      <td>2</td>
      <td>P</td>
      <td>1089</td>
      <td>1</td>
      <td>13</td>
      <td>2</td>
    </tr>
    <tr>
      <th>21</th>
      <td>D</td>
      <td>1364</td>
      <td>-9</td>
      <td>0</td>
      <td>0.5</td>
      <td>P</td>
      <td>1227</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1012</td>
      <td>-14</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1221</td>
      <td>-4</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>P</td>
      <td>1508</td>
      <td>-2</td>
      <td>-2</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1132</td>
      <td>-2</td>
      <td>6</td>
      <td>1</td>
      <td>D</td>
      <td>1009</td>
      <td>-8</td>
      <td>-28</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>D</td>
      <td>1220</td>
      <td>-5</td>
      <td>-11</td>
      <td>0</td>
      <td>P</td>
      <td>1551</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1420</td>
      <td>10</td>
      <td>12</td>
      <td>2</td>
      <td>P</td>
      <td>1508</td>
      <td>19</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>24</th>
      <td>D</td>
      <td>1143</td>
      <td>-46</td>
      <td>-31</td>
      <td>0</td>
      <td>P</td>
      <td>1089</td>
      <td>-17</td>
      <td>-10</td>
      <td>0</td>
      <td>D</td>
      <td>1700</td>
      <td>-7</td>
      <td>-13</td>
      <td>0</td>
      <td>P</td>
      <td>1705</td>
      <td>-11</td>
      <td>-21</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>D</td>
      <td>1322</td>
      <td>-24</td>
      <td>-51</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-28</td>
      <td>-25</td>
      <td>0</td>
      <td>P</td>
      <td>1685</td>
      <td>7</td>
      <td>13</td>
      <td>2</td>
      <td>D</td>
      <td>1227</td>
      <td>-32</td>
      <td>-22</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>D</td>
      <td>1099</td>
      <td>-17</td>
      <td>-26</td>
      <td>0</td>
      <td>P</td>
      <td>1441</td>
      <td>-3</td>
      <td>-27</td>
      <td>0</td>
      <td>P</td>
      <td>1803</td>
      <td>-18</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1685</td>
      <td>11</td>
      <td>21</td>
      <td>2</td>
    </tr>
    <tr>
      <th>27</th>
      <td>D</td>
      <td>1321</td>
      <td>-47</td>
      <td>-29</td>
      <td>0</td>
      <td>P</td>
      <td>1644</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1705</td>
      <td>18</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1346</td>
      <td>-15</td>
      <td>-7</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [81]:
generate_rounds(stevenson)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="5" halign="left">Round 1</th>
      <th colspan="5" halign="left">Round 2</th>
      <th colspan="5" halign="left">Round 3</th>
      <th colspan="5" halign="left">Round 4</th>
    </tr>
    <tr>
      <th></th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>D</td>
      <td>1551</td>
      <td>-5</td>
      <td>-6</td>
      <td>0</td>
      <td>P</td>
      <td>1220</td>
      <td>-8</td>
      <td>-8</td>
      <td>0</td>
      <td>D</td>
      <td>1346</td>
      <td>16</td>
      <td>21</td>
      <td>2</td>
      <td>P</td>
      <td>1644</td>
      <td>8</td>
      <td>28</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>P</td>
      <td>1346</td>
      <td>9</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1420</td>
      <td>-6</td>
      <td>14</td>
      <td>1</td>
      <td>P</td>
      <td>1553</td>
      <td>14</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1220</td>
      <td>-10</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>P</td>
      <td>1419</td>
      <td>-1</td>
      <td>0</td>
      <td>0.5</td>
      <td>D</td>
      <td>1685</td>
      <td>17</td>
      <td>10</td>
      <td>2</td>
      <td>P</td>
      <td>1099</td>
      <td>-6</td>
      <td>-3</td>
      <td>0</td>
      <td>D</td>
      <td>1551</td>
      <td>-1</td>
      <td>-13</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>P</td>
      <td>1221</td>
      <td>4</td>
      <td>-2</td>
      <td>1</td>
      <td>D</td>
      <td>1700</td>
      <td>28</td>
      <td>25</td>
      <td>2</td>
      <td>P</td>
      <td>1441</td>
      <td>2</td>
      <td>40</td>
      <td>2</td>
      <td>D</td>
      <td>1143</td>
      <td>2</td>
      <td>18</td>
      <td>2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>P</td>
      <td>1705</td>
      <td>17</td>
      <td>26</td>
      <td>2</td>
      <td>D</td>
      <td>1506</td>
      <td>-17</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1089</td>
      <td>6</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1549</td>
      <td>6</td>
      <td>0</td>
      <td>1.5</td>
    </tr>
    <tr>
      <th>5</th>
      <td>D</td>
      <td>1227</td>
      <td>-15</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1364</td>
      <td>-12</td>
      <td>-4</td>
      <td>0</td>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>-6</td>
      <td>1</td>
      <td>P</td>
      <td>1420</td>
      <td>-3</td>
      <td>-2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P</td>
      <td>1685</td>
      <td>46</td>
      <td>31</td>
      <td>2</td>
      <td>D</td>
      <td>1508</td>
      <td>24</td>
      <td>35</td>
      <td>2</td>
      <td>D</td>
      <td>1322</td>
      <td>-1</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-2</td>
      <td>-18</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>P</td>
      <td>1649</td>
      <td>5</td>
      <td>11</td>
      <td>2</td>
      <td>D</td>
      <td>1009</td>
      <td>8</td>
      <td>8</td>
      <td>2</td>
      <td>D</td>
      <td>1549</td>
      <td>-1</td>
      <td>-2</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>10</td>
      <td>-3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>D</td>
      <td>1098</td>
      <td>-4</td>
      <td>2</td>
      <td>1</td>
      <td>P</td>
      <td>1322</td>
      <td>-8</td>
      <td>-3</td>
      <td>0</td>
      <td>P</td>
      <td>1227</td>
      <td>7</td>
      <td>-10</td>
      <td>1</td>
      <td>D</td>
      <td>1553</td>
      <td>4</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>P</td>
      <td>1132</td>
      <td>15</td>
      <td>23</td>
      <td>2</td>
      <td>D</td>
      <td>1553</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>D</td>
      <td>1221</td>
      <td>-7</td>
      <td>10</td>
      <td>1</td>
      <td>P</td>
      <td>1700</td>
      <td>32</td>
      <td>22</td>
      <td>2</td>
    </tr>
    <tr>
      <th>10</th>
      <td>P</td>
      <td>1803</td>
      <td>47</td>
      <td>29</td>
      <td>2</td>
      <td>D</td>
      <td>1419</td>
      <td>-3</td>
      <td>1</td>
      <td>1</td>
      <td>D</td>
      <td>1506</td>
      <td>15</td>
      <td>9</td>
      <td>2</td>
      <td>P</td>
      <td>1364</td>
      <td>23</td>
      <td>19</td>
      <td>2</td>
    </tr>
    <tr>
      <th>11</th>
      <td>P</td>
      <td>1700</td>
      <td>24</td>
      <td>51</td>
      <td>2</td>
      <td>D</td>
      <td>1221</td>
      <td>8</td>
      <td>3</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>1</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1441</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>12</th>
      <td>D</td>
      <td>1012</td>
      <td>-9</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1549</td>
      <td>-23</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1009</td>
      <td>-16</td>
      <td>-21</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>15</td>
      <td>7</td>
      <td>2</td>
    </tr>
    <tr>
      <th>13</th>
      <td>P</td>
      <td>1553</td>
      <td>9</td>
      <td>0</td>
      <td>1.5</td>
      <td>D</td>
      <td>1132</td>
      <td>12</td>
      <td>4</td>
      <td>2</td>
      <td>P</td>
      <td>1551</td>
      <td>-17</td>
      <td>-18</td>
      <td>0</td>
      <td>D</td>
      <td>1321</td>
      <td>-23</td>
      <td>-19</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>D</td>
      <td>1089</td>
      <td>1</td>
      <td>0</td>
      <td>1.5</td>
      <td>P</td>
      <td>1321</td>
      <td>3</td>
      <td>-1</td>
      <td>1</td>
      <td>D</td>
      <td>1508</td>
      <td>38</td>
      <td>78</td>
      <td>2</td>
      <td>P</td>
      <td>1506</td>
      <td>5</td>
      <td>8</td>
      <td>2</td>
    </tr>
    <tr>
      <th>15</th>
      <td>D</td>
      <td>1549</td>
      <td>-5</td>
      <td>-12</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>6</td>
      <td>-14</td>
      <td>1</td>
      <td>P</td>
      <td>1649</td>
      <td>-10</td>
      <td>-12</td>
      <td>0</td>
      <td>D</td>
      <td>1132</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>16</th>
      <td>P</td>
      <td>1506</td>
      <td>17</td>
      <td>-7</td>
      <td>1</td>
      <td>D</td>
      <td>1705</td>
      <td>3</td>
      <td>27</td>
      <td>2</td>
      <td>D</td>
      <td>1098</td>
      <td>-2</td>
      <td>-40</td>
      <td>0</td>
      <td>P</td>
      <td>1322</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>D</td>
      <td>1441</td>
      <td>-17</td>
      <td>7</td>
      <td>1</td>
      <td>P</td>
      <td>1099</td>
      <td>17</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1321</td>
      <td>-15</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1419</td>
      <td>-5</td>
      <td>-8</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>-24</td>
      <td>-35</td>
      <td>0</td>
      <td>P</td>
      <td>1419</td>
      <td>-38</td>
      <td>-78</td>
      <td>0</td>
      <td>D</td>
      <td>1649</td>
      <td>-19</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>P</td>
      <td>1420</td>
      <td>5</td>
      <td>12</td>
      <td>2</td>
      <td>D</td>
      <td>1346</td>
      <td>23</td>
      <td>23</td>
      <td>2</td>
      <td>P</td>
      <td>1220</td>
      <td>1</td>
      <td>2</td>
      <td>2</td>
      <td>D</td>
      <td>1099</td>
      <td>-6</td>
      <td>0</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>20</th>
      <td>P</td>
      <td>1009</td>
      <td>5</td>
      <td>6</td>
      <td>2</td>
      <td>D</td>
      <td>1649</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
      <td>D</td>
      <td>1364</td>
      <td>17</td>
      <td>18</td>
      <td>2</td>
      <td>P</td>
      <td>1089</td>
      <td>1</td>
      <td>13</td>
      <td>2</td>
    </tr>
    <tr>
      <th>21</th>
      <td>D</td>
      <td>1364</td>
      <td>-9</td>
      <td>0</td>
      <td>0.5</td>
      <td>P</td>
      <td>1227</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1012</td>
      <td>-14</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1221</td>
      <td>-4</td>
      <td>-9</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>P</td>
      <td>1508</td>
      <td>-2</td>
      <td>-2</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>-1</td>
      <td>-7</td>
      <td>0</td>
      <td>P</td>
      <td>1132</td>
      <td>-2</td>
      <td>6</td>
      <td>1</td>
      <td>D</td>
      <td>1009</td>
      <td>-8</td>
      <td>-28</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>D</td>
      <td>1220</td>
      <td>-5</td>
      <td>-11</td>
      <td>0</td>
      <td>P</td>
      <td>1551</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
      <td>D</td>
      <td>1420</td>
      <td>10</td>
      <td>12</td>
      <td>2</td>
      <td>P</td>
      <td>1508</td>
      <td>19</td>
      <td>9</td>
      <td>2</td>
    </tr>
    <tr>
      <th>24</th>
      <td>D</td>
      <td>1143</td>
      <td>-46</td>
      <td>-31</td>
      <td>0</td>
      <td>P</td>
      <td>1089</td>
      <td>-17</td>
      <td>-10</td>
      <td>0</td>
      <td>D</td>
      <td>1700</td>
      <td>-7</td>
      <td>-13</td>
      <td>0</td>
      <td>P</td>
      <td>1705</td>
      <td>-11</td>
      <td>-21</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>D</td>
      <td>1322</td>
      <td>-24</td>
      <td>-51</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-28</td>
      <td>-25</td>
      <td>0</td>
      <td>P</td>
      <td>1685</td>
      <td>7</td>
      <td>13</td>
      <td>2</td>
      <td>D</td>
      <td>1227</td>
      <td>-32</td>
      <td>-22</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>D</td>
      <td>1099</td>
      <td>-17</td>
      <td>-26</td>
      <td>0</td>
      <td>P</td>
      <td>1441</td>
      <td>-3</td>
      <td>-27</td>
      <td>0</td>
      <td>P</td>
      <td>1803</td>
      <td>-18</td>
      <td>-11</td>
      <td>0</td>
      <td>D</td>
      <td>1685</td>
      <td>11</td>
      <td>21</td>
      <td>2</td>
    </tr>
    <tr>
      <th>27</th>
      <td>D</td>
      <td>1321</td>
      <td>-47</td>
      <td>-29</td>
      <td>0</td>
      <td>P</td>
      <td>1644</td>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>D</td>
      <td>1705</td>
      <td>18</td>
      <td>11</td>
      <td>2</td>
      <td>P</td>
      <td>1346</td>
      <td>-15</td>
      <td>-7</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>

In [84]:
def formatted_tab_df(tab_df):
    return generate_teams(tab_df).join(generate_rounds(tab_df)).join(generate_summary(tab_df))

In [85]:
formatted_tab_df(stevenson)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">Team</th>
      <th colspan="5" halign="left">Round 1</th>
      <th colspan="3" halign="left">Round 2</th>
      <th>...</th>
      <th colspan="3" halign="left">Round 4</th>
      <th colspan="7" halign="left">Summary</th>
    </tr>
    <tr>
      <th></th>
      <th>Number</th>
      <th>Name</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Side</th>
      <th>Opponent</th>
      <th>Ballot 1</th>
      <th>...</th>
      <th>Ballot 1</th>
      <th>Ballot 2</th>
      <th>Total Ballots</th>
      <th>Ballots Won</th>
      <th>Ballots Lost</th>
      <th>Ballots Tied</th>
      <th>CS</th>
      <th>OCS</th>
      <th>PD</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1009</td>
      <td>University of Maryland, College Park</td>
      <td>D</td>
      <td>1551</td>
      <td>-5</td>
      <td>-6</td>
      <td>0</td>
      <td>P</td>
      <td>1220</td>
      <td>-8</td>
      <td>...</td>
      <td>8</td>
      <td>28</td>
      <td>2</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>16.0</td>
      <td>66.0</td>
      <td>46</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1012</td>
      <td>University of Maryland, College Park</td>
      <td>P</td>
      <td>1346</td>
      <td>9</td>
      <td>1</td>
      <td>2</td>
      <td>D</td>
      <td>1420</td>
      <td>-6</td>
      <td>...</td>
      <td>-10</td>
      <td>3</td>
      <td>1</td>
      <td>6</td>
      <td>2</td>
      <td>0</td>
      <td>12.5</td>
      <td>77.0</td>
      <td>32</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1089</td>
      <td>Stevenson</td>
      <td>P</td>
      <td>1419</td>
      <td>-1</td>
      <td>0</td>
      <td>0.5</td>
      <td>D</td>
      <td>1685</td>
      <td>17</td>
      <td>...</td>
      <td>-1</td>
      <td>-13</td>
      <td>0</td>
      <td>2</td>
      <td>5</td>
      <td>1</td>
      <td>20.0</td>
      <td>53.0</td>
      <td>3</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1098</td>
      <td>University of Maryland, Baltimore County</td>
      <td>P</td>
      <td>1221</td>
      <td>4</td>
      <td>-2</td>
      <td>1</td>
      <td>D</td>
      <td>1700</td>
      <td>28</td>
      <td>...</td>
      <td>2</td>
      <td>18</td>
      <td>2</td>
      <td>7</td>
      <td>1</td>
      <td>0</td>
      <td>13.0</td>
      <td>79.5</td>
      <td></td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1099</td>
      <td>University of Maryland, Baltimore County</td>
      <td>P</td>
      <td>1705</td>
      <td>17</td>
      <td>26</td>
      <td>2</td>
      <td>D</td>
      <td>1506</td>
      <td>-17</td>
      <td>...</td>
      <td>6</td>
      <td>0</td>
      <td>1.5</td>
      <td>5</td>
      <td>2</td>
      <td>1</td>
      <td>14.0</td>
      <td>70.0</td>
      <td>30</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1132</td>
      <td>University of Scranton</td>
      <td>D</td>
      <td>1227</td>
      <td>-15</td>
      <td>-23</td>
      <td>0</td>
      <td>P</td>
      <td>1364</td>
      <td>-12</td>
      <td>...</td>
      <td>-3</td>
      <td>-2</td>
      <td>0</td>
      <td>1</td>
      <td>7</td>
      <td>0</td>
      <td>12.5</td>
      <td>56.5</td>
      <td>-63</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1143</td>
      <td>Iona College</td>
      <td>P</td>
      <td>1685</td>
      <td>46</td>
      <td>31</td>
      <td>2</td>
      <td>D</td>
      <td>1508</td>
      <td>24</td>
      <td>...</td>
      <td>-2</td>
      <td>-18</td>
      <td>0</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>17.0</td>
      <td>52.0</td>
      <td></td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1220</td>
      <td>Haverford College</td>
      <td>P</td>
      <td>1649</td>
      <td>5</td>
      <td>11</td>
      <td>2</td>
      <td>D</td>
      <td>1009</td>
      <td>8</td>
      <td>...</td>
      <td>10</td>
      <td>-3</td>
      <td>1</td>
      <td>5</td>
      <td>3</td>
      <td>0</td>
      <td>20.5</td>
      <td>62.0</td>
      <td>36</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1221</td>
      <td>Haverford College</td>
      <td>D</td>
      <td>1098</td>
      <td>-4</td>
      <td>2</td>
      <td>1</td>
      <td>P</td>
      <td>1322</td>
      <td>-8</td>
      <td>...</td>
      <td>4</td>
      <td>9</td>
      <td>2</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>22.5</td>
      <td>54.0</td>
      <td>-3</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1227</td>
      <td>College of William &amp; Mary</td>
      <td>P</td>
      <td>1132</td>
      <td>15</td>
      <td>23</td>
      <td>2</td>
      <td>D</td>
      <td>1553</td>
      <td>-1</td>
      <td>...</td>
      <td>32</td>
      <td>22</td>
      <td>2</td>
      <td>5</td>
      <td>3</td>
      <td>0</td>
      <td>9.5</td>
      <td>73.5</td>
      <td>87</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1321</td>
      <td>Columbia University</td>
      <td>P</td>
      <td>1803</td>
      <td>47</td>
      <td>29</td>
      <td>2</td>
      <td>D</td>
      <td>1419</td>
      <td>-3</td>
      <td>...</td>
      <td>23</td>
      <td>19</td>
      <td>2</td>
      <td>7</td>
      <td>1</td>
      <td>0</td>
      <td>17.0</td>
      <td>67.0</td>
      <td></td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1322</td>
      <td>Columbia University</td>
      <td>P</td>
      <td>1700</td>
      <td>24</td>
      <td>51</td>
      <td>2</td>
      <td>D</td>
      <td>1221</td>
      <td>8</td>
      <td>...</td>
      <td>1</td>
      <td>9</td>
      <td>2</td>
      <td>8</td>
      <td>0</td>
      <td>0</td>
      <td>13.0</td>
      <td>79.5</td>
      <td>98</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1346</td>
      <td>Washington Adventist University</td>
      <td>D</td>
      <td>1012</td>
      <td>-9</td>
      <td>-1</td>
      <td>0</td>
      <td>P</td>
      <td>1549</td>
      <td>-23</td>
      <td>...</td>
      <td>15</td>
      <td>7</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>20.5</td>
      <td>56.0</td>
      <td>-71</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1364</td>
      <td>St. Vincent College</td>
      <td>P</td>
      <td>1553</td>
      <td>9</td>
      <td>0</td>
      <td>1.5</td>
      <td>D</td>
      <td>1132</td>
      <td>12</td>
      <td>...</td>
      <td>-23</td>
      <td>-19</td>
      <td>0</td>
      <td>3</td>
      <td>4</td>
      <td>1</td>
      <td>18.5</td>
      <td>62.0</td>
      <td>-52</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1419</td>
      <td>La Salle University</td>
      <td>D</td>
      <td>1089</td>
      <td>1</td>
      <td>0</td>
      <td>1.5</td>
      <td>P</td>
      <td>1321</td>
      <td>3</td>
      <td>...</td>
      <td>5</td>
      <td>8</td>
      <td>2</td>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>14.5</td>
      <td>74.5</td>
      <td></td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1420</td>
      <td>La Salle University</td>
      <td>D</td>
      <td>1549</td>
      <td>-5</td>
      <td>-12</td>
      <td>0</td>
      <td>P</td>
      <td>1012</td>
      <td>6</td>
      <td>...</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>17.5</td>
      <td>58.5</td>
      <td>-42</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1441</td>
      <td>New York University</td>
      <td>P</td>
      <td>1506</td>
      <td>17</td>
      <td>-7</td>
      <td>1</td>
      <td>D</td>
      <td>1705</td>
      <td>3</td>
      <td>...</td>
      <td>-1</td>
      <td>-9</td>
      <td>0</td>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>20.0</td>
      <td>60.5</td>
      <td>-12</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1506</td>
      <td>Johns Hopkins University</td>
      <td>D</td>
      <td>1441</td>
      <td>-17</td>
      <td>7</td>
      <td>1</td>
      <td>P</td>
      <td>1099</td>
      <td>17</td>
      <td>...</td>
      <td>-5</td>
      <td>-8</td>
      <td>0</td>
      <td>3</td>
      <td>5</td>
      <td>0</td>
      <td>22.0</td>
      <td>65.5</td>
      <td>-19</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1508</td>
      <td>Franklin and Marshall College</td>
      <td>D</td>
      <td>1644</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>P</td>
      <td>1143</td>
      <td>-24</td>
      <td>...</td>
      <td>-19</td>
      <td>-9</td>
      <td>0</td>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>15.5</td>
      <td>60.5</td>
      <td>-199</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1549</td>
      <td>George Washington University</td>
      <td>P</td>
      <td>1420</td>
      <td>5</td>
      <td>12</td>
      <td>2</td>
      <td>D</td>
      <td>1346</td>
      <td>23</td>
      <td>...</td>
      <td>-6</td>
      <td>0</td>
      <td>0.5</td>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>15.5</td>
      <td>72.5</td>
      <td>60</td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1551</td>
      <td>George Washington University</td>
      <td>P</td>
      <td>1009</td>
      <td>5</td>
      <td>6</td>
      <td>2</td>
      <td>D</td>
      <td>1649</td>
      <td>1</td>
      <td>...</td>
      <td>1</td>
      <td>13</td>
      <td>2</td>
      <td>8</td>
      <td>0</td>
      <td>0</td>
      <td>14.0</td>
      <td>72.5</td>
      <td>70</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>1553</td>
      <td>Stevenson University</td>
      <td>D</td>
      <td>1364</td>
      <td>-9</td>
      <td>0</td>
      <td>0.5</td>
      <td>P</td>
      <td>1227</td>
      <td>1</td>
      <td>...</td>
      <td>-4</td>
      <td>-9</td>
      <td>0</td>
      <td>2</td>
      <td>5</td>
      <td>1</td>
      <td>18.5</td>
      <td>63.0</td>
      <td>-35</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1644</td>
      <td>Towson University</td>
      <td>P</td>
      <td>1508</td>
      <td>-2</td>
      <td>-2</td>
      <td>0</td>
      <td>D</td>
      <td>1803</td>
      <td>-1</td>
      <td>...</td>
      <td>-8</td>
      <td>-28</td>
      <td>0</td>
      <td>1</td>
      <td>7</td>
      <td>0</td>
      <td>11.0</td>
      <td>56.0</td>
      <td>-44</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1649</td>
      <td>Fordham University Rose Hill</td>
      <td>D</td>
      <td>1220</td>
      <td>-5</td>
      <td>-11</td>
      <td>0</td>
      <td>P</td>
      <td>1551</td>
      <td>-1</td>
      <td>...</td>
      <td>19</td>
      <td>9</td>
      <td>2</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>18.0</td>
      <td>67.5</td>
      <td>24</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1685</td>
      <td>St. Vincent College</td>
      <td>D</td>
      <td>1143</td>
      <td>-46</td>
      <td>-31</td>
      <td>0</td>
      <td>P</td>
      <td>1089</td>
      <td>-17</td>
      <td>...</td>
      <td>-11</td>
      <td>-21</td>
      <td>0</td>
      <td>0</td>
      <td>8</td>
      <td>0</td>
      <td>10.5</td>
      <td>69.5</td>
      <td>-156</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1700</td>
      <td>Brooklyn College</td>
      <td>D</td>
      <td>1322</td>
      <td>-24</td>
      <td>-51</td>
      <td>0</td>
      <td>P</td>
      <td>1098</td>
      <td>-28</td>
      <td>...</td>
      <td>-32</td>
      <td>-22</td>
      <td>0</td>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>20.0</td>
      <td>46.0</td>
      <td>-162</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>1705</td>
      <td>City College of New York, CUNY</td>
      <td>D</td>
      <td>1099</td>
      <td>-17</td>
      <td>-26</td>
      <td>0</td>
      <td>P</td>
      <td>1441</td>
      <td>-3</td>
      <td>...</td>
      <td>11</td>
      <td>21</td>
      <td>2</td>
      <td>2</td>
      <td>6</td>
      <td>0</td>
      <td>12.5</td>
      <td>56.5</td>
      <td>-70</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>1803</td>
      <td>Bye-Buster Team</td>
      <td>D</td>
      <td>1321</td>
      <td>-47</td>
      <td>-29</td>
      <td>0</td>
      <td>P</td>
      <td>1644</td>
      <td>1</td>
      <td>...</td>
      <td>-15</td>
      <td>-7</td>
      <td>0</td>
      <td>4</td>
      <td>4</td>
      <td>0</td>
      <td>12.0</td>
      <td>61.0</td>
      <td>-61</td>
      <td>4.0</td>
    </tr>
  </tbody>
</table>
<p>28 rows × 29 columns</p>
</div>